const actiontypes = {
  LOGIN: "LOGIN",
  SET_USER: "SET_USER",
  SET_FACTORY: "SET_FACTORY",
  SET_PLANT: "SET_PLANT",
  SET_PRODUCT: "SET_PRODUCT",
  SET_MACHINE: "SET_MACHINE",
  SET_SNACK_DATA: "SET_SNACK_DATA",
  SET_LOADING: "SET_LOADING",
  SET_BASE_URL: "SET_BASE_URL",
  SET_LOGGED_USER: "SET_LOGGED_USER",
  SET_PLANT_LIST: "SET_PLANT_LIST",
  SET_PRODUCT_LIST: "SET_PRODUCT_LIST",
  SET_MACHINE_LIST: "SET_MACHINE_LIST",
  SET_LINE_LIST: "SET_LINE_LIST",
  SET_INDEPT_MACHINE: "SET_INDEPT_MACHINE",
};

export default actiontypes;
